# Generated by Django 5.0.2 on 2024-03-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattest', '013_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_of_question', models.TextField()),
                ('number_of_question', models.IntegerField()),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.AlterField(
            model_name='test',
            name='answers',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
