# Generated by Django 5.0.2 on 2024-04-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattest', '0014_question_alter_test_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_matter',
            field=models.BooleanField(default=True),
        ),
    ]
