# Generated by Django 5.0.2 on 2024-04-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattest', '0015_question_is_matter'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.TextField(blank=True),
        ),
    ]
