# Generated by Django 5.0.2 on 2024-04-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattest', '0016_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_matter',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
    ]
