# Generated by Django 5.0.2 on 2024-04-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cattest', '0017_remove_question_is_matter_alter_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='type_of_kotik',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
