# Generated by Django 5.0.2 on 2024-02-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_kotik', models.IntegerField(null=True)),
                ('current_question', models.IntegerField(default=1)),
                ('user_id', models.IntegerField()),
                ('answers', models.CharField(blank=True)),
            ],
            options={
                'db_table': 'current_test',
            },
        ),
    ]
